[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
default-run = "day1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1"
path = "day1/src/main.rs"

[dependencies]
